version: "3.8"

services:
  django_app:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - static-volume:/static
    depends_on:
      - postgres
  bot_app:
    build:
      context: ./bot
    ports:
      - "8001:8001"

    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${PG_NAME}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    env_file:
      - .env
    container_name: postgres
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/default.conf
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
        - django_app
        - bot_app
    restart: always
  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot certonly --webroot -w /var/www/certbot --email shukhratbekovb@gmail.com --agree-tos --no-eff-email -d shukhratbekov.uz -d bot.shukhratbekov.uz; sleep 12h & wait $${!}; done;'"
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt

volumes:
  postgres_data:
  certbot-etc:
  certbot-var:
  static-volume: